# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-22 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attending',
            field=models.BooleanField(default=True),
        ),
    ]
