# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='tribe',
            field=models.CharField(choices=[('0', 'Wernberg'), ('1', 'Larson'), ('2', 'Both')], default=2, max_length=1),
        ),
    ]
