# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_auto_20171022_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='guests.HouseHold'),
        ),
    ]
