# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_auto_20171022_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='attending',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes'), ('3', 'Maybe')], default=1, max_length=1),
        ),
    ]
