# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_auto_20171022_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='tribe',
            field=models.CharField(choices=[('0', 'Wernberg'), ('1', 'Larson'), ('2', 'Both')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='guest',
            name='attending',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes'), ('2', 'Maybe')], default=1, max_length=1),
        ),
    ]
