# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-29 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_auto_20171028_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='tribe',
            field=models.CharField(choices=[('0', 'Wernberg'), ('1', 'Larson'), ('2', 'Both'), ('3', 'Larson-Wernberg')], default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='household',
            name='tribe',
            field=models.CharField(choices=[('0', 'Wernberg'), ('1', 'Larson'), ('2', 'Both'), ('3', 'Larson-Wernberg')], default=1, max_length=1),
        ),
    ]
