# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-21 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_auto_20171029_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='save_the_date',
            field=models.BooleanField(default=False, verbose_name='Save The Date Sent'),
        ),
    ]
