# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_auto_20180519_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='food_choice',
            field=models.IntegerField(choices=[(0, 'STEAK'), (1, 'FISH'), (2, 'VEGGIE'), (3, 'KIDS'), (999, 'NONE')], default=999),
        ),
    ]
